name: keep streamlit alive 4

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:
  push:

jobs:
  
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit app
        run: curl -s https://projetodashboardgestaodasaguasufsc.streamlit.app/
